- config/config_test.go
- config/misc.go
To get the instance id of the pod, we were first checking that the last token (split by -) is an integer or not, in which case we returned that. If not, we used the third to last token (to handle the case for gw ha pods) to get  the index. However, this breaks down if the ha pods end up receiving a suffix which is an integer. This change fixes that issue.
> fix: handle the case when the gateway suffix (in HA mode) ends up being a number

- stats/statsd.go
Adding logs pertaining to StatsD client creation and retries
> chore: add logs during StatsD client creation

- .gitignore
- stats/statsd.go
Before this change, the error variable declared in the start function syntax is modified by the goroutine at line 48. Since we are returning nil at the end, err variable is set to nil. leading to a potential data race by main routine and go routine
Test this in [go playground](https://go.dev/play/p/L2u7NfBpQCb)
I got to know about it when I was testing this [pr](https://github.com/rudderlabs/rudder-sources/pull/929) for a race condition.
These are the logs, i got when i ran rudder-sources in race condition
```
==================
WARNING: DATA RACE
Write at 0x00c0004884f0 by main goroutine:
github.com/rudderlabs/rudder-go-kit/stats.(*statsdStats).Start()
/Users/ganeshvarmaraghavaraju/rudderstack/rudder-sources/vendor/github.com/rudderlabs/rudder-go-kit/stats/statsd.go:69 +0x5b8 …
```
> fix: race condition for err variable when statsd start is called

- stats/internal/otel/otel.go
- stats/internal/otel/otel_test.go
- stats/internal/otel/prometheus/config.go
- stats/internal/otel/prometheus/exporter.go
- stats/internal/otel/testdata/otel-collector-config.yaml
- stats/otel.go
- stats/otel_test.go
- stats/testdata/otel-collector-config.yaml
Small refactoring to have the service instance ID consistent across all 3 stats modes under the label `instanceName`. I also simplified a bit the prometheus exporter and removed an unnecessary metric (i.e. `otel_scope_info`) that was giving me troubles with the tests and that we are not using nor planning to use.
< [Notion Link](https://www.notion.so/rudderstacks/Fix-instanceName-across-stats-27f92841d5d3450d8ff83cd20cf32031)>
> fix: instanceName consistency

- stats/internal/otel/otel_test.go
- stats/internal/otel/prometheus/exporter.go
- stats/otel.go
- stats/otel_test.go
- stats/stats.go
- stats/statsd.go
This is to address an error that happens when the same label is set both at the resource level and at the metric label. 
The underlying Prometheus client is the one raising the error [here](https://github.com/prometheus/client_golang/blob/main/prometheus/desc.go#L140).
The proposal is to remove the duplicate at the metric level (so the resource will take precedence) and to log it in order to take action if needed/wanted.
In the gRPC version the resource attributes take precedence and the metric is not lost.
< [Notion Link](https://www.notion.so/rudderstacks/Deploy-otel-to-prousmt-cc0a56cc658c4a2f985fe766e71ca83c) >
> fix: otel prometheus duplicated attributes

- filemanager/s3manager.go
- filemanager/s3manager_test.go
Fixing data race. Additional changes include:
* Exporting type to allow for variable declaration. Encapsulation is preserved.
* Breaking some long lines.
* Removed `defer` inside `for` loop (bad practice).
* Generalized error casting instead of using `awserr`.
* Removed dependency to `awserr`.
< [Linear Link](https://linear.app/rudderstack/issue/PIPE-115/s3-manager-data-race) >
> fix: s3 manager data race

- filemanager/gcsmanager.go
Fixing data race.
< [Linear Link](https://linear.app/rudderstack/issue/PIPE-119/run-warehouse-tests-with-race) >
> fix: gcs manager race

- testhelper/docker/resource/postgres.go
- testhelper/docker/resource/postgres/config.go
Increase the default shared memory size for postgres container to 512MB from 64MB and provide an additional option for overriding it
> chore: configurable shared memory size for postgres container

- config/atomic_benchmark_test.go
- config/config.go
- config/config_test.go
- config/hotreloadable.go
- config/load.go
- config/reloadable_benchmark_test.go
- logger/config.go
- logger/factory.go
- logger/logger.go
Now that we're running warehouse tests with the `-race` flags (used in order to prevent races to go to production), we're seeing random failures in some tests (e.g. snowflake integrations) with hot-reloadable configs.
This PR tries to address the issue in a backwards compatible manner and by providing a succint alternative to use the new API without having to burden ourselves with locking and unlocking mutexes each time we have to deal with such variables.
```
==================
WARNING: DATA RACE
Write at 0x000008f21110 by goroutine 3191:
github.com/rudderlabs/rudder-go-kit/config.(*Config).RegisterDurationConfigVariable()
/home/francesco/go/pkg/mod/github.com/rudderlabs/rudder-go-kit@v0.15.7/config/hotreloadable.go:159 +0x66f
github.com/rudderlabs/rudder-go-kit/config.RegisterDurationCon …
```
> fix: register reloadable config variables

- config/config.go
- config/hotreloadable.go
- config/load.go
Internal callers which have already acquired a read lock on `vLock` are now using `isSetInternal` which doesn't acquire any lock.
> fix: config deadlock by trying to acquire a read lock twice

- config/config.go
- config/config_test.go
- config/hotreloadable.go
- config/load.go
`config#registerXxxVar` was acquiring a read lock on `vLock` and after that, another read lock was being acquired on the same lock by `config#GetXxx` before the previous read lock was released, causing a deadlock.
- Simplifying locking by only acquiring locks when necessary (limited scope) and once
- Adding a test to protect against a future regression
- Avoiding to register a reloadable pointer more than once
> fix: another config deadlock by trying to acquire a read lock twice

- filemanager/s3manager.go
- filemanager/s3manager_test.go
expose GetSession method of S3
https://linear.app/rudderstack/issue/PIPE-318/prepare-a-local-error-index-in-the-replay-task-rudder-sources
> chore: expose S3Manager#GetSession

- testhelper/docker/resource/minio.go
- testhelper/docker/resource/minio/config.go
- testhelper/docker/resource/minio_test.go
- testhelper/docker/resource/testdata/minio.object
Standardising the way we are creating minio docker containers in our tests
> chore: add a docker resource for minio

- throttling/memory_gcra.go
- throttling/memory_gcra_test.go
Extending cache expiration for limiter to account for burst and cost values greater than the rate.
> fix: memory gcra limiter inconsistency when rate < cost < burst

- stats/memstats/stats.go
- stats/memstats/stats_test.go
The existing method for verifying stats `.Get` during tests was limiting and cumbersome.
You could only retrieve a specific combination of name and tags. This way:
* You could not test if other metrics were created during the execution. https://github.com/rudderlabs/rudder-server/pull/3974#discussion_r1378951251
* It is difficult to find the problem if the particular combination of name+tags is missing.
For these reasons, I wanted a way to retrieve a collection of metrics registered to the store.
* Introduce `.GetAll` which returns a Metrics array, containing all possible name+stats combinations captured using the storage.
* Introduce `.GetByName` which returns the subset that belongs to a measurement name.
`Metric` type is a bit special, it has
*  `Value` just float used for …
> feat: provide memstat methods to assist on testing (pipe-538)

- .github/workflows/verify.yml
- Makefile
- internal/scripts/install-golangci-lint.sh
Standardizing approach with rudder-server.
< [Linear_Link](https://linear.app/rudderstack/issue/PIPE-565/use-same-golangci-lint-approach-in-go-kit-no-docker) >
> chore: golangci-lint no docker

- .github/dependabot.yml
Updating Dependabot configuration as per Jaeger example to group OTEL dependencies.
< [Linear_Link](https://linear.app/rudderstack/issue/PIPE-733/dependabot-otel) >
> chore: dependabot otel

- .github/dependabot.yml
Updating Dependabot configuration as per Jaeger example to group OTEL dependencies.
< [Linear_Link](https://linear.app/rudderstack/issue/PIPE-733/dependabot-otel) >
> chore: adding sdk to otel group

- testhelper/docker/resource/postgres/config.go
- testhelper/docker/resource/postgres/postgres.go
- testhelper/docker/resource/postgres/postgres_test.go
- testhelper/docker/resource/types.go
- throttling/util_test.go
- Using three levels of validation for container startup, (1) pg_isready, (2) db.Ping and (3) SQL query execution
- In case of a test failure, the container's status and logs will be printed for debugging purposes.
- Added support for setting memory limit and `oom-kill-disable`
> chore: unexpected EOF errors with postgres container

- .github/workflows/tests.yaml
- go.mod
- go.sum
- testhelper/docker/docker.go
- testhelper/docker/resource/transformer/transformer.go
- testhelper/docker/resource/transformer/transformer_backend_config.go
- testhelper/docker/resource/transformer/transformer_test.go
- testhelper/httptest/httptest.go
- testhelper/httptest/httptest_test.go
Add support to mock config backend with transformer resource initialisation. This will allow tests to run independent of actual config backend. Test will not fail even if control plane is down.
https://linear.app/rudderstack/issue/PIPE-804/mock-config-be-for-transformer-resource-in-go-kit
> feat: add mock config BE support for transformer

- async/single_sender.go
- async/single_sender_test.go
- go.mod
- testhelper/docker/resource/mysql/config.go
- testhelper/docker/resource/mysql/mysql.go
- testhelper/docker/resource/mysql/mysql_test.go
- testhelper/docker/resource/postgres/config.go
- testhelper/docker/resource/postgres/postgres.go
- testhelper/docker/resource/postgres/postgres_test.go
`async.SingleSender` is a helper for sending and receiving values to and from a channel between 2 separate goroutines, a sending and a receiving goroutine, while at the same time supporting the following scenarios::
1. The sending goroutine in case the parent context is canceled should be able to notify the receiver goroutine about the error through the channel.
2. The receiving goroutine should be able to stop listening from the channel (a.k.a. leave) at any point.
3. The sending goroutine shouldn't be blocked trying to send to the channel when the receiver has left it.
4. Receiver's departure should act as a context cancellation signal to the sending goroutine, i.e. it should stop working.
> feat: add async.SingleSender and a new docker resource for mysql

- testhelper/docker/resource/transformer/transformer.go
- testhelper/docker/resource/transformer/transformer_backend_config.go
- testhelper/httptest/httptest.go
- testhelper/httptest/httptest_test.go
Blocking https://github.com/rudderlabs/rudder-server/pull/4473
- Export http request handler for BE Config, so that if someone wants to implement its own http client for BE Config for transformer need not to implement their own handler again.
- Export NewUnstartedHttpServer to initialise a server that will be started(start serving request) at a later point in time
https://linear.app/rudderstack/issue/PIPE-884/move-backend-config-unavailability-test-to-rudder-server-integration
> chore: export config BE handler for transformer, and unstarted http test server

- throttling/lua/gcra.lua
- throttling/lua/sortedset.lua
- throttling/memory_gcra.go
- throttling/memory_gcra_test.go
- throttling/throttling.go
- throttling/throttling_test.go
Adding support for `retryAfter` to all throttling algorithms.
This should be useful in the src-router for example where we want to estabilish a consumption rate throttling mechanism.
Without this we would be limited to in-memory algorithms only and we would have to spam the CPU by calling `Allow()` in a loop until we get `true`. 
Thanks to `retryAfter`, once we get `false` (we hit the limit) we can simply sleep for the amount of microseconds specified by the algorithm and then, at the next call, we should be allowed to get through. Unfortunately the GCRA algorithms aren't very precise so sometimes we might get throttled regardless of the sleep. With the "sorted set" algorithm this never happens (in single-threaded programs).
* The existing API has not been changed. I have instead added a …
> feat: throttling with retryAfter

- .github/workflows/labeler.yaml
- .github/workflows/pr-description-enforcer.yaml
- .github/workflows/semantic-pr.yaml
- .github/workflows/tests.yaml
- .github/workflows/verify.yml
- sync/group.go
- sync/group_test.go
A sync group(`g.Go(f func() error)`) that tries to not initialise new goroutines or running the function provided(`f`) if the context's cancelled.
Otherwise works just like `golang.org/x/sync/errgroup`.
Use `NewEagerGroup(ctx, n)` for a new eager group, panics otherwise.
Limits only if `n > 0`
Added github workflow concurrency groups as well.
< Replace_with_Linear_Link >
> feat: sync.EagerGroup

- sqlutil/monitor.go
- sqlutil/monitor_test.go
- Adding support for monitoring database ([*sql.DB](https://pkg.go.dev/database/sql#DB)) using the [DBStats](https://pkg.go.dev/database/sql#DBStats) provided.
- Resolves PIPE-894
> feat: monitor sql database

- sftp/client.go
- sftp/mock_sftp/mock_sftp_client.go
- sftp/sftp.go
- sftp/sftp_test.go
- Added support for remote file paths in function parameter and removed support for remote directory parameter.
- The remote file path parameter provides more flexibility. Since it will be an input in the UI, we can directly pass it to the Upload function, whereas with the remote directory, we had to explicitly build the path.
- Create a remote directory if it does not exist.
Resolved INT-2048
https://linear.app/rudderstack/issue/INT-2048/go-kit-create-remote-directory-in-sftp
> feat: add remoteFilePath support and create remote directory in sftp

- sftp/client.go
- sftp/mock_sftp/mock_sftp_client.go
- sftp/sftp.go
- sftp/sftp_test.go
**Problem**
- AWS SFTP server do not support opening files read/write at the same time. 
- Using GO SFTP Client `Create`, AWS SFTP server is throwing this error :- `SSH_FX_OP_UNSUPPORTED`
- Similar issue reported while using Create with AWS SFTP server.
- https://github.com/pkg/sftp/issues/305
**Solution**
- Use Go SFTP [OpenFile](https://forum.golangbridge.org/t/client-create-test-txt-error-ssh-fx-op-unsupported/27284)
- This is compatible with non AWS SFTP servers too.
Resolves INT-2048
https://linear.app/rudderstack/issue/INT-2048/go-kit-sftp-enhancements
> fix: file creation on aws sftp servers

- testhelper/docker/resource/redis/redis.go
We are supporting loading a custom docker repository for Redis. Now if someone wants to load a custom redis docker repo, they would need to use `WithRepository`
Resolves INT-2095
> feat: add support for custom redis docker repository

- config/config.go
- config/config_test.go
- config/env.go
In a 1 hour profile `config.ConfigKeyToEnv` is taking near to 8.4minutes of execution, which can be seen from flame graph.
Internally this function is using regex which is we can be replaced and performance can be optimised. After replacing regex with simple for loops we can see improvements in the performance. attaching benchmark results here:
```
Old Code:  
BenchmarkConfigKeyToEnv-12    	 1287674	       922.6 ns/op	     265 B/op	      10 allocs/op
New Code: 
BenchmarkConfigKeyToEnv-12    	 9455137	       118.8 ns/op	      56 B/op	       3 allocs/op
```
https://linear.app/rudderstack/issue/PIPE-1103/optimise-function-configconfigkeytoenv-in-rudder-go-kit
> chore: optimise function config.ConfigKeyToEnv

- stats/otel.go
Exposes otel version so downstream dependencies won't need to import open tel package for testing.
For example here https://github.com/rudderlabs/rudder-server/blob/f4b5d114508db4795e71a13eeb9596c7ebd1838b/integration_test/tracing/tracing_test.go#L692z
rudder-server depending on `go.opentelemetry.io/otel` causes issues when [upgrading dependencies](https://github.com/rudderlabs/rudder-server/pull/4713).
By using exposing otelVersion from stats, we remove this minor unnecessary dependency.
https://linear.app/rudderstack/issue/PIPE-1123/address-vulnerability-issues
> chore: expose otel version from stats library

- cachettl/cachettl.go
- resourcettl/cache.go
- resourcettl/cache_test.go
Introducing a new specialty cache for resources which need to be closed/cleaned-up after their expiration.
This new cache keeps track of the resources' usage and makes sure that expired resources are not cleaned up while they are still in use and cleaned up only when they are no longer needed.
Internally it uses a `cachettl.Cache` which has been extended with an `OnEvicted` callback.
Resources with any of following methods can be managed by the cache and cleaned up appropriately:
- `Cleanup()`
- `Close()`
- `Close() error`
- `Stop()`
- `Stop() error`
> feat: introduce a ttl cache for resources

- stats/memstats/stats.go
- stats/memstats/stats_test.go
Found this issue while writing tests for a histogram metric. I did expect to receive 20 measurements for a metric, but instead I got only one.
It turns out that since a new stat was created every time, the measurement was getting overridden. 
Note that this might have a breaking behaviour downstream, but tests that use `.GetAll` or `.GetByName` should have and test all measurements captured.
https://linear.app/rudderstack/issue/PIPE-1161/fix-memstats-bug
resolves PIPE-1161
> fix: memstats new stat should reuse measurement

- testhelper/docker/resource/minio/minio.go
- testhelper/docker/resource/minio/minio_test.go
Add content method to testhelper minio resource, to avoid code repetition in tests.
https://linear.app/rudderstack/issue/PIPE-1179/rudder-go-kit-testhelper-miniocontents
resolves PIPE-1179
> feat: minio testhelper add content method

- testhelper/docker/resource/scylla/config.go
- testhelper/docker/resource/scylla/scylla.go
- testhelper/docker/resource/scylla/scylla_test.go
Add scylla test helper in `rudder-go-kit`
Fixes PIPE-1367
> feat: create scylla resource

- filemanager/gcsmanager.go
Disabling telemetry in GCS client.
< Replace_with_Linear_Link >
> chore: disable telemetry in gcs client

- filemanager/digitaloceanmanager.go
- filemanager/miniomanager.go
- filemanager/s3manager.go
`Manager is truncated: ...` should be a debug log instead of Info
Resolves PRO-3247
> chore: isTruncated should be a debug log

- testhelper/docker/resource/internal/ports.go
`host.docker.internal` in linux, by default, resolves to `172.17.0.1`
> fix: docker containers don't listen to host.docker.internal

- testhelper/docker/resource/internal/ports.go
- testhelper/docker/resource/postgres/postgres_test.go
Binding only to `127.0.0.1` (and `host.docker.internal` in case of `linux`)
regression introduced by #614
> fix: docker containers listening on ipv6

- testhelper/gittest/gittest.go
- testhelper/gittest/gittest_test.go
- testhelper/gittest/testdata/gitrepo/README.md
- testhelper/httptest/httptest.go
- testhelper/httptest/httptest_test.go
- `gittest`: provides a test helper for creating a git server that serves a git repository.
- `httptest`: provides similar functionality to the `net/http/httptest` package, but with some additional features: (1) It allows you to listen to all interfaces, not just localhost and (2) for TLS servers, it allows you to specify the host name to use in the certificate.
> feat: introduce gittest

- go.mod
- testhelper/gittest/gittest.go
- testhelper/gittest/gittest_test.go
> feat: method for fetching latest commit from gittest server

- .github/workflows/tests.yaml
- testhelper/docker/resource/scylla/config.go
- testhelper/docker/resource/scylla/scylla.go
Have Scylla integration test run without IPv6.
< [Linear_Link](https://linear.app/rudderstack/issue/PIPE-1564/%5Bgo-kit%5D-have-scylla-integration-test-run-without-ipv6) >
> test: scylla no ipv6

- stats/statsd_test.go
Fixes flaky test that got introduced here https://github.com/rudderlabs/rudder-go-kit/pull/648
https://linear.app/rudderstack/issue/PRI-48/database-sql-stats
> fix: flaky test: slice comparison to ignore element order

- .github/workflows/verify.yml
- Makefile
- filemanager/digitaloceanmanager.go
- filemanager/s3manager.go
- go.mod
- testhelper/docker/resource/mysql/mysql.go
- testhelper/docker/resource/postgres/postgres.go
Regular update to the latest go version, also `golangci-lint` for compatibility reasons, the previous version was not compatible go1.23
https://linear.app/rudderstack/issue/PIPE-1577/rudder-go-kit-upgrade-go-version
> chore: update go and linter version

- testhelper/docker/resource/transformer/transformer.go
- Add WIthEnv for docker transformer.
> chore: add support for WithEnv and WithRepository for transformer resource

- testhelper/gittest/gittest.go
- testhelper/gittest/gittest_test.go
> feat: allow retrieval of commits for tags

- compress/benchmark_test.go
More benchmarks for compression/decompression.
< Linear_Link >
> chore: compression benchmarks

- testhelper/docker/resource/pulsar/pulsar.go
Use loopback address as host address as localhost is not reachable. 
-
> chore: update pulsar endpoint to use 127.0.0.1

- maxprocs/maxprocs.go
- maxprocs/maxprocs_test.go
Given that setting K8s limits has [proven](https://home.robusta.dev/blog/stop-using-cpu-limits) to be causing performance issues, we can only set CPU requests.
**Considerations:**
* In order to contain costs we want to set CPU requests to a value that makes sense to handle normal traffic for a given namespace. 
* We should not use K8s CPU limits to avoid throttling.
* We should not waste unused CPU if there is demand for it.
* The services should be able to use more than the requested CPUs (if there is some available) to better handle spikes of traffic.
* Setting `GOMAXPROCS` to a very high number or leaving it unset will set it to a very high value (e.g. `64`) causing serious GC performance degradation.
* What we have now in `ingestion-svc` and `src-router` is that `GOMAXPROCS` = …
> feat: max procs

- Makefile
- go.mod
- throttling/options.go
- throttling/throttling.go
- throttling/throttling_test.go
Adding a way to customize tags in throttler.
Updating go version as well to fix a few vulnerabilities in `net/http@go1.23.1` and `crypto/x509@go1.23.1`.
See [here](https://github.com/rudderlabs/rudder-go-kit/actions/runs/13031397974/job/36351341283?pr=730).
> chore: throttling tagger

- go.mod
- stats/statsd.go
An unecessary read lock on `clientsLock` mutex during `Stop()` could cause a deadlock in the following scenario:
- `Stop()` is called by `goroutineA` which acquires the read lock
- Stat collection `goroutineB` is requesting a new stat. In such a case a full lock is required but it is not possible, causing `goroutineB` to block.
- `goroutineA` is waiting for `goroutineB` to finish so that `Stop()` returns, but `goroutineA` is blocked.
During `Stop()` `clientsLock` is not necessary to be read-locked, since there is nothing to protect at this phase.
> fix(stats): deadlock during stats stop

- mem/internal/cgroup/mem.go
- mem/internal/cgroup/mem_test.go
- mem/internal/cgroup/testdata/cgroups_v1_mem_limit_proc_self/sys/fs/cgroup/memory/pid1/memory.stat
- mem/mem.go
- mem/mem_test.go
In some scenarios, it might be preferable to monitor `container_memory_rss` instead of `container_memory_working_set_bytes` due to the following issue: https://github.com/kubernetes/kubernetes/issues/43916
Now `mem.Stat` contains `RSS` memory in bytes, along with some derived methods:
- `RSSPercent` - returns the percentage of RSS memory
- `AvailableIgnoreCache` - returns the available memory in bytes, ignoring cache memory. This is calculated as [Total] - [RSS]
- `AvailableIgnoreCachePercent` - returns the available memory in percentage, ignoring cache memory. This is calculated as [Total] - [RSS]
> feat: include rss memory in calculated mem stats

- go.mod
- testhelper/docker/resource/transformer/transformer.go
- testhelper/docker/resource/transformer/transformer_test.go
In order to run a private transformer docker image, we need to pass an auth credential to `setup` functions.
We added an option to pass docker auth credentials.
This is needed to run the ingestion-svc test using private docker images of the transformer
Resolves INT-2926
https://linear.app/rudderstack/issue/INT-2926/automating-integration-tests-as-part-of-pr
> chore: add options to run image using docker credentials

- go.mod
- trie/benchmark_test.go
- trie/trie.go
- trie/trie_test.go
This PR introduces a trie data structure to support efficient prefix string matching operations. It also updates the Go version to v1.23.8 to address some security vulnerabilities
- NewTrie() - Creates a new empty trie
- Insert(word string) - Adds a word to the trie
- GetMatchedPrefixWord(input string) - Returns (bool, string) indicating if a prefix match was found and the matching prefix
- HasMatchedPrefixWords(input string) - Returns bool indicating if any prefix matches a complete word
- Not concurrent safe, requires external synchronization for concurrent access
- Trims words before inserting them to the trie.
[Resolves OBS-823](https://linear.app/rudderstack/issue/OBS-823/add-trie-implementation-in-go-kit
)
> feat: add trie data structure for prefix string matching

- kafkaclient/producer.go
It can be beneficial to be able to override the default value if 1MB
> chore: expose kafka producer batch bytes configuration property

- maputil/maputil.go
- maputil/maputil_test.go
This PR adds the MapLookup utility function to the maputil package. This function provides a convenient way to traverse nested map[string]interface{} structures using a sequence of keys.
The implementation is the same as in rudder-server [here](https://github.com/rudderlabs/rudder-server/blob/master/utils/misc/misc.go#L822).
< Linear_Link >
> feat: add MapLookup function

- netutil/ip_ranges.go
- netutil/ip_ranges_test.go
This PR creates a new package `netutil` which generates CIDR ranges from an array of CIDRs and provides a helper function to check if an IP is part of those CIDR ranges
Fixes PIPE-2064
> feat: introduce netutil package

- retryablehttp/retryablehttp.go
- retryablehttp/retryablehttp_test.go
add a retryable HTTP client with exponential backoff
pipe-2105
> feat: add a retryable HTTP client with exponential backoff

- jsonrs/sonnet.go
- sonnet's marshaller doesn't have streaming issues like its unmarshaller does
- sonnet's marshaller is 2x faster than jsoniter
- sonnet's marshaller is more compatible to std json library than jsoniter is
> chore: sonnet should use its own marshaller in jsonrs

- config/config_bool.go
- config/config_changedetect.go
- config/config_duration.go
- config/config_float64.go
- config/config_int.go
- config/config_int64.go
- config/config_string.go
- config/config_stringmap.go
- config/config_stringslice.go
When performing advanced change detection for non-reloadable config values, we shouldn't be modifying the original value itself, but a copy of the original value. 
Otherwise, we are modifying a non-reloadable config variable and we are also causing a DATA RACE detection errors, since values are being modified while they are being read.
> fix: non-reloadable config values getting updated during change detection

- filemanager/s3manager.go
- filemanager/s3manager_test.go
- filemanager/s3manager_v2.go
- Continue to create the S3 session in s3managerV2 even if fetching the region fails to keep the behaviour consistent with v1. 
- skip setting session region as it's already being done in `NewSimpleSessionConfig`
< Linear_Link >
> chore: skip setting session region and ignore region fetch errors

- httputil/client.go
- httputil/client_test.go
- Introduce DefaultHttpClient with pre-configured transport settings
- Add HttpClientOptions type for customizing HTTP client
- Implement WithTimeout and WithTransport options
- Update tests to cover new functionality
pipe-2219
> feat: add default HTTP client and options for custom transport and timeout

- testhelper/docker/resource/etcd/etcd.go
- testhelper/docker/resource/kafka/kafka.go
`bitnami` images have been moved to `bitnamilegacy`
> chore: switch from bitnami to bitnamilegacy docker images

- .ai-agent/guidelines.md
- .claude/agents/code-reviewer.md
- .claude/agents/test-runner.md
- .claude/settings.local.json
- CLAUDE.md
- maxprocs/maxprocs.go
- maxprocs/maxprocs_test.go
At the moment the `maxprocs` doesn't support VPA in-place.
In this PR I'm addressing this, using a file watcher. We would then need to configure our pods on K8s as such:
```yaml
volumeMounts:
- name: podinfo
mountPath: /etc/podinfo
volumes:
- name: podinfo
downwardAPI:
items:
- path: "cpu_request"
resourceFieldRef:
containerName: client-container
resource: requests.cpu
divisor: 1m
```
I added the usual AI guidelines to this repo as well.
< Fixes [PIPE-2451](https://linear.app/rudderstack/issue/PIPE-2451/go-kit-maxprocs-to-support-vpa-in-place) >
https://rudderlabs.slack.com/archives/C02AASYS6R1/p1758803093901929
> chore: maxprocs to support vpa in-place
